### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by IgorPolyakov** [hcodes/yaspeller#103]
echo "Hello, world" | yaspeller --stdin
TypeError: Cannot destructure property `config` of 'undefined' or 'null'.

Версии пакетов:
- npm 6.1.0
- yaspeller 4.2.0
- node v9.0.0

OS
- Linux 4.15.0-20-generic 16.04.1-Ubuntu x86_64 GNU/Linux

**Comment by hcodes** [comment]
v4.2.1

**Comment by IgorPolyakov** [comment]
Спасибо)
