### ISSUE TITLE
Возможная проблема с emoji

### ISSUE THREAD

**Issue by NeroMorto** [hcodes/yaspeller#105]
Заметил, проблему на https://tech.yandex.ru/speller/
Если в тексте присутствует emoji, то проверка умирает (предположение) на сервере, либо работает очень долго ( не дождался окончания данного процесса)
Да я видел, что сервис работает только с UTF-8, но возможно такие ситуации имеет смысл обрабатывать.

Протестировать можно с помощь такого текста:
>ппривет
>
>3) Восssпроизвести не получилось, но 🕷️ чутье подсказывает мне, что тут должны быть проблемы

Первую ошибку испрвляем/пропускаем - видим что процесс "остановился"
Повторяем тест, но убираем паучка - доходим до второй ошибки (орфографической).
На фронте никаких ошибок (в консольке) замечено не было.

**Comment by hcodes** [comment]
Лучше о проблеме сервиса tech.yandex.ru/speller/ написать через обратную связь: https://tech.yandex.ru/speller/doc/dg/concepts/troubleshooting-docpage/

Yaspeller использует API Yandex.Speller’а.

**Comment by NeroMorto** [comment]
Отписал по ссылке, тут проблему закрываю.

**Comment by hcodes** [comment]
Спасибо.
