### ISSUE TITLE
Слово с заглавной буквой не проходит проверку, если правило начинается с пустого выражения

### ISSUE THREAD

**Issue by vessd** [hcodes/yaspeller#107]
```bash
$ yaspeller --version
4.2.1
```
```bash
$ cat .yaspellerrc 
{
    "dictionary": [
        "(|саб)реддит"
    ] 
}
```
```bash
$ cat test.md 
Сабреддит
сабреддит
Реддит
реддит
```
```bash
$ yaspeller test.md 
✗ /home/sergey/projects/test.md 103 ms
-----
Typos: 1
1. Реддит (3:1, suggest: Кредит)
-----

Checking finished: 0.386 sec.
```

**Comment by hcodes** [comment]
В словарь лучше занести отдельно два слова:
- `сабреддит`
- `реддит`

**Comment by hcodes** [comment]
Логика работы такая, если в слове первый символ буква, то эта буква заменяется на `[xX]` для удобства. Например, `сабреддит` -> `/[сС]абредит/`.

В вашем случае, первый символ `(` — замены не будет. Вы можете написать собственные регулярки в словаре без вмешательства спеллера.
Это не баг, это фича.
