### ISSUE TITLE
"Переиспользование" считается опечаткой несмотря на наличие в словаре

### ISSUE THREAD

**Issue by mkpankov** [hcodes/yaspeller#111]
```text
± % ➜  yaspeller --only-errors *.md _posts
✗ /home/mkpankov/rustycrate/_posts/2017-06-11-oop-in-rust.md 242 ms
-----
Typos: 1
1. т.е. переиспользование (71:46, suggest: теперь е использование)
-----


mkpankov@mkpankov-ThinkPad-x240 ~/rustycrate [master *]
± % ➜  yaspeller --version
5.0.0
```

`.yaspellerrc`:

```
{
    "lang": "ru",
    "dictionary": [
...
        "переиспользование"
    ],
...
```

**Comment by hcodes** [comment]
http://speller.yandex.net/services/spellservice.json/checkText?text=%D1%82.%D0%B5.%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

**Comment by mkpankov** [comment]
Ну я знаю, словарь-то перегружать результат должен? :)

**Comment by hcodes** [comment]
Нужно переводить на API с https. Там такой проблемы нет. Займусь в ближайшее время.

**Comment by hcodes** [comment]
Раньше работало из-за неправильной проверки #106.

**Comment by mkpankov** [comment]
Понял, будем ждать https!

**Comment by hcodes** [comment]
Осталось всего 4 опции: https://tech.yandex.ru/speller/doc/dg/reference/speller-options-docpage/
Было 10: https://github.com/hcodes/yandex-speller/blob/master/lib/yandex-speller.js#L76

**Comment by hcodes** [comment]
Нет, осталась только одна рабочая опция IGNORE_URLS.

Плюс, в новом API — новый подход: «Кроме того, Спеллер не придирается к новым словам, ещё не попавшим в словари»
https://tech.yandex.ru/speller/

Итого, всё равно придётся рано или поздно переходить на новое API.

**Comment by mkpankov** [comment]
Я думаю нам новый подход подойдёт как раз.

**Comment by hcodes** [comment]
Новое API не подходит (. Несколько раз пытался перейти, тесты не проходят, ни одна опция в API не работает, плохая поддержка HTML. В коротких текстах есть ошибки, если добавить больше слов в текст, то ошибки магическим образом пропадают.

**Comment by hcodes** [comment]
Ошибка Yandex Speller API.
