### ISSUE TITLE
sitemap.xml - TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by croupier** [hcodes/yaspeller#112]
OS: Windows 10 Pro 64
Node: v8.11.3
Shell: mintty  (MINGW64 git-bash from Git 64 for Windows)/CDM/PowerShell

Error:
`$ yaspeller https://www.mozilla.org/ru/sitemap.xml
C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:341
        text.replace(new RegExp(item.word + '(?:' + letters + '|$)', 'g'), function($0, index) {
             ^

TypeError: Cannot read property 'replace' of undefined
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:341:14
    at Array.forEach (<anonymous>)
    at Object.addPositions (C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:333:10)
    at onResource (C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\tasks.js:22:19)
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:311:45
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:250:13
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\lib\yaspeller.js:107:9
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\node_modules\async\dist\async.js:3888:9
    at C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\node_modules\async\dist\async.js:473:16
    at iterateeCallback (C:\Users\croupier\AppData\Roaming\npm\node_modules\yaspeller\node_modules\async\dist\async.js:992:24)`

**Comment by hcodes** [comment]
v5.0.1
