### ISSUE TITLE
Писать в CLI как добавить слово в словарь

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#114]
**Текущий вывод:**

```
✗ /home/ai/Dev/nanoevents/api.md 478 ms
-----
Typos: 1
1. Interfac (21:1, suggest: Interface)
-----

✓ /home/ai/Dev/nanoevents/CHANGELOG.md 316 ms
✓ /home/ai/Dev/nanoevents/README.md 304 ms
```

**Проблема:** когда люди присылают PR и Yaspeller не пропускает PR, они не знают как исправить.

**Анализ:** инструмент крутой, не не очень известный. Люди не понимают, что произошло и как это исправить.

**Предложение:**

1. Выводить `Spelling check:` чтобы было понятно, что за проверка.
2. В случае ошибки снизу выводить `Fix typo or add word to dictionary at package.json if you are sure about spelling` (с реальным путём для конфига).

**Пример:** вот как мы делаем в Size Limit столкнувшись с такой же проблемой

![example](https://user-images.githubusercontent.com/19343/56772800-77d2e080-6789-11e9-9be9-d01a4db2e9a5.png)

**Comment by hcodes** [comment]
Хорошая идея, надо сделать.

**Comment by hcodes** [comment]
v5.1.0
