### ISSUE TITLE
Возможность подправить текст перед проверкой

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#119]
У меня половина словаря — это имена людей из `CHANGELOG.md`. Вот было бы круто, если бы перед проверкой на орфографию можно было бы вырезать:

```js
if (file === 'CHANGELOG.md') {
  return content.replace(/\(by [^)]+\)/g, '')
} else {
  return content
}
```

Но я точно не знаю какой API можно придумать? Может опцию `--hook hook.js`? Или может я могу как-то сдеать это в своём `yaspeller-ci` уже через JS API?

**Comment by hcodes** [comment]
https://github.com/hcodes/yaspeller#--ignore-text-regexp

**Comment by ai** [comment]
Идеально

**Comment by ai** [comment]
А есть какой-то способ понять какие слова в словаре больше не нужны?

**Comment by hcodes** [comment]
Если удалить словари из конфига и запустить эту команду:
`yaspeller -l ru ./docs/  --report=error_dictionary`
То спеллер создаст `./yaspeller_error_dictionary.json` файл с опечатками. Потом останется сравнить словарь из конфига и файл с опечатками.

**Comment by ai** [comment]
Спасибо
