### ISSUE TITLE
Добавить возможность предобработки текста перед проверкой

### ISSUE THREAD

**Issue by vitalets** [hcodes/yaspeller#127]
Кейс такой: я хочу проверить орфографию во всех текстах навыка для Алисы.
Там используется  символ "+" [для указания ударений](https://yandex.ru/dev/dialogs/alice/doc/speech-tuning-docpage/).
Например: `остр+ота` 
В результате yaspeller считает это двумя разными словами. 
Было бы полезно иметь опцию для вырезания символов либо указания функции предобработки текста.

**Comment by hcodes** [comment]
https://github.com/hcodes/yaspeller#--ignore-text-regexp

test.txt:
```
остр+ота
```


```bash
yaspeller -l ru --ignore-text="(?<=[А-ЯЁа-яё])\+(?=[А-ЯЁа-яё])" test.txt
```

**Comment by vitalets** [comment]
Круто, спасибо! 
Предлагаю в доку `ignore-text-regexp` этот пример добавить, т.к. по описанию такую регулярку не сочинишь)
