### ISSUE TITLE
Удалить request

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#130]
Проект `request` [был закрыт](https://github.com/request/request/issues/3142). Надо переходить на `fetch()`.

Сейчас `yarn install` пишет в консоль:

```
warning yaspeller > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by hcodes** [comment]
Надо так надо.

**Comment by hcodes** [comment]
v6.0.3
