### ISSUE TITLE
Help debugging issue with repeated word

### ISSUE THREAD

**Issue by iranzo** [hcodes/yaspeller#134]
Hi,
I'm working on adding yaspeller to check markdown files and for one of them, it complains about repeated word 'the'.

I'm using the `--ignore-digits --ignore-urls --find-repeat-words` flags and just complains about that duplicated 'the' word, which if course, doesn't appear in editor when searching for:

- `the the`
- `the \``

Any hint on how to get the intermediate text that yaspeller uses for finding a duplicate word to see where the issue could be?

**Comment by hcodes** [comment]
There is an option `--debug`, but it won't be enough. If only add console.log to the yaspeller package code.

**Comment by hcodes** [comment]
Can you attach a problem file?

**Comment by iranzo** [comment]
Hi, I was trying the --debug but didn't happen

In my case it was a phrase like "the `blablabla` the "

Which when the code block was removed, caused the repeated 'the the', but was a long article and was  really really hard to find it as there was no indication of line for the issue

**Comment by hcodes** [comment]
https://github.com/hcodes/yaspeller/pull/141

**Comment by iranzo** [comment]
Using latest version, now it doesn't fail, but I would like to have seen the repeated word.
```sh
[DEBUG] Get/check config.
Spelling check:
[DEBUG] get: /home/iranzo/www/content/prueba.en.md
[DEBUG] post text -> Yandex.Speller API: /home/iranzo/www/content/prueba.en.md
[DEBUG]
    request: 0
    format: markdown
    apiFormat: html
    lang: en,ru
    options: [object Object]
    text: the the the the ship
✓ /home/iranzo/www/content/prueba.en.md 220 ms
No errors.
Checking finished: 0.465 sec.

```

with the text:

~~~raw
the `blablabla` the



the the ship

~~~


Which IMHO should fail, isn't it?

**Comment by hcodes** [comment]
v6.1.0
