### ISSUE TITLE
Support for regular expressions in files to check

### ISSUE THREAD

**Issue by iranzo** [hcodes/yaspeller#135]
Scenario:

I want to have a website with dual languages, I wanted to use yaspeller to check only 'en' articles to avoid false errors on another languages

I would like yaspeller to check files wich are named "*.en.*" for the extensions I might indicate via the current extensions.

Is that doable?

**Comment by hcodes** [comment]
yaspeller "*.en.md"
For complex cases, use the full force of system commands.

**Comment by iranzo** [comment]
Thanks!
