### ISSUE TITLE
Возможность выводить слова-результаты в порядке их появления в тексте

### ISSUE THREAD

**Issue by nickkolok** [hcodes/yaspeller#15]
Прошу возможности выводить слова-результаты в порядке их появления в тексте (либо сортировки по частоте встречаемости).

**Comment by hcodes** [comment]
Согласен, уберу сортировку из результатов.

**Comment by nickkolok** [comment]
Совсем убирать, имхо, не нужно, достаточно ключика а-ля --no-sort

**Comment by xoxulin** [comment]
И желательно с номерами строк, как делают линтеры)

**Comment by ihoru** [comment]
+1
+1 за строки

**Comment by hcodes** [comment]
Со строками не так всё просто.
Например, markdown-файлы преобразуются в HTML, а потом передаются в API.
И строки с ошибками из API не будут соответствовать со строками до обработки исходного файла.
В API также ограничение на размер, не более 10000 символов.
...
Посмотрю, что можно сделать с другими форматами.

**Comment by ihoru** [comment]
@hcodes можно найти ошибочные слова в тексте, которые вернет сервис, а там и строка будет известна...
Хотя это уже откровеннаяая хотелка.

**Comment by hcodes** [comment]
v3.0.0
