### ISSUE TITLE
Error: getaddrinfo ENOTFOUND speller.yandex.net speller.yandex.net:80

### ISSUE THREAD

**Issue by MichaelEvtushenko** [hcodes/yaspeller#159]
Hi hcodes,

I've installed **yaspeller** as a global dependency, but when I run a command `yaspeller SOME_FILE`, I got the error:
`Error: getaddrinfo ENOTFOUND speller.yandex.net speller.yandex.net:80`

Any ideas how can I fix it?

**Comment by hcodes** [comment]
Is the url available in the browser?
http://speller.yandex.net/services/spellservice.json/checkText?text=hello

**Comment by MichaelEvtushenko** [comment]
No, there is no access to Yandex (API) in Ukraine. Well, I've found the solution: simply using VPN to switch to another country, where Yandex is available. So it works fine for me.
