### ISSUE TITLE
yaspeller scans non .md  files when filesExtensions are set to ".md" only  

### ISSUE THREAD

**Issue by limorl** [hcodes/yaspeller#167]
yaspeller scans the file .github/workflows/linter.yml, though expected only .md files to be scanned.
I tried  adding "*.yml" to excludeFiles, but it still picks the linter.yml file and scans it.

Here's my configuration file:
 {
    "lang": "en",
    "ignoreTags": ["code", "script"],
    "ignoreUrls": true,
    "ignoreUppercase": true,
    "fileExtensions": [
        ".md"
    ],
    "excludeFiles": [
        ".git",
        "node_modules"
    ],
    "dictionary": [
        "dataset",
        "datasets",
        "GitHub",
        "lifecycle",
        "maintainer",
        "maintainers",
        "repo",
        "repos",
        "screenshots",
        "Terraform"
    ]
}

**Comment by hcodes** [comment]
I'm closing the bug, I didn't get a response.

**Comment by bdsoha** [comment]
I am encountering the same issue while on tag `v8.0.1`.
