### ISSUE TITLE
Add support of declensions

### ISSUE THREAD

**Issue by ignovak** [hcodes/yaspeller#17]
Currently I can't add a word to the dictionary, supposing it'll take care of all its declensions. For example, if I add `тайтл` to dictionary, yaspeller won't ignore `тайтла`, `тайтлов` etc, though it would be great if it did.
Yes, I suppose that this task might be really hard, so I can suggest more simple solution: to add support of wildcards to dictionary. So in my example I could just add `тайтл*` to dictionary and it would work as I want.

**Comment by hcodes** [comment]
Need support for regular expressions.
Will be as follows:
```
[
'/тайтл(а|е|ов)/'
]
```

**Comment by hcodes** [comment]
v1.1.0
