### ISSUE TITLE
Ignore case of words in dictionary

### ISSUE THREAD

**Issue by ignovak** [hcodes/yaspeller#18]
Yaspeller doesn't ignore `Конфиг` if I add `конфиг` to dictionary (and vice versa). I wish it did.

**Comment by hcodes** [comment]
There is a difference in the words of `Москва` and `москва`.

Also need the support of regular expressions in the dictionary.
And will be something like this:
```
[
    '/конфиг/i',
    '/(К|к)онфиг/'
]
```

**Comment by hcodes** [comment]
v1.1.0
