### ISSUE TITLE
Ignore code in Markdown

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#19]
I add `"ignoreTags": ["code"]` to config, but Yaspeller still shows class names from my docs:

```
Use `AtRule` class
```

Maybe we should process Markdown to HTML before check to be able to prevent tag content?

**Comment by ai** [comment]
@hcodes кстати, большое спасибо за инструмент. Добавляю его в Travis CI для PostCSS и Автопрефиксера.

**Comment by hcodes** [comment]
По умолчанию тег `code` игнорируется https://github.com/hcodes/yaspeller/blob/master/.yaspellerrc.default.json#L7

`ignoreTags` работает только для формата `html` и `markdown`, наверное, надо в документации про это написать.

Важный момент для CI, у API.Спеллера есть ограничения - http://legal.yandex.ru/speller_api/
```
3.2. Яндекс оставляет за собой право устанавливать любые лимиты и ограничения, включая далее перечисленное, но не ограничиваясь этим:
 -   на количество обращений к Сервису - в размере 10 тысяч обращений в сутки;
 -   на объем проверяемого текста - в размере 10 миллионов символов в сутки.
```
Про это тоже надо написать в документации.

**Comment by ai** [comment]
Разобрался. У меня не определялся формат автоматически, поэтому и не работали теги.

Кстати, странно. Файлы идут с расширением `.md`.

**Comment by hcodes** [comment]
Сейчас формат определяется по контенту.
Согласен, учёт расширения файла не помешает, сделаю.

**Comment by hcodes** [comment]
v1.1.0
