### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by aloskutov** [hcodes/yaspeller#199]
Завершается с ошибкой при проверки markdown текстов:

```text
F:\work\project\node_modules\yaspeller\lib\yaspeller.js:459
        if (!posA.length || !posB.length) {
                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at F:\work\project\node_modules\yaspeller\lib\yaspeller.js:459:19
    at Array.sort (<anonymous>)
    at Object.sortByPositions (F:\work\project\node_modules\yaspeller\lib\yaspeller.js:443:10)
    at onResource (F:\work\project\node_modules\yaspeller\lib\tasks.js:25:19)
    at F:\work\project\node_modules\yaspeller\lib\tasks.js:131:21
    at F:\work\project\node_modules\yaspeller\lib\yaspeller.js:211:21
    at F:\work\project\node_modules\yaspeller\lib\yaspeller.js:116:9
    at F:\work\project\node_modules\async\dist\async.js:3683:19
    at wrapper (F:\work\project\node_modules\async\dist\async.js:273:20)
    at iterateeCallback (F:\work\project\node_modules\async\dist\async.js:429:28)

Node.js v20.9.0
```

Локально исправлял добавлением проверки:

```js
if (!posA || !posB) {
  return -1;
}
```

**Comment by hcodes** [comment]
@aloskutov очень нужна ссылка на md-файл или сам файл, пока не могу воспроизвести локально баг.

**Comment by aloskutov** [comment]
Определил конкретный файл, это происходит из-за фразы на японском こんにちは、世界！
[index.md](https://github.com/hcodes/yaspeller/files/13328225/index.md)

---

И есть ещё один баг, он появился после перехода на новый API. Для некоторых обзацев предлагается замена первого слова на тоже самое слово, но с двумя пробелами перед ним. 2, 5 и 6 "опечатки" для приложенного файла. Или оформить его в отдельный issue?

```
❯ yaspeller f:\work\project\src\articles\javascript\character-encoding-cheat-sheet\index.md
Spelling check:
[ERR] F:\work\project\src\articles\javascript\character-encoding-cheat-sheet\index.md 1251 ms
-----
Too many errors

Typos: 7
1. njk (6:17, suggest: ngk, kak, njv)
2. Следует (39:1, suggest:  Следует)
3. кодированных (187:296, suggest: закодированных)
4. URI (count: 3, suggest: URL)
5. В (suggest:  В)
6. Для (suggest:  Для)
7. метатега (suggest: мета тега)
-----
```

**Comment by hcodes** [comment]
> Определил конкретный файл, это происходит из-за фразы на японском こんにちは、世界！ [index.md](https://github.com/hcodes/yaspeller/files/13328225/index.md)
> 
> И есть ещё один баг, он появился после перехода на новый API. Для некоторых обзацев предлагается замена первого слова на тоже самое слово, но с двумя пробелами перед ним. 2, 5 и 6 "опечатки" для приложенного файла. Или оформить его в отдельный issue?
> 
> ```
> ❯ yaspeller f:\work\project\src\articles\javascript\character-encoding-cheat-sheet\index.md
> Spelling check:
> [ERR] F:\work\project\src\articles\javascript\character-encoding-cheat-sheet\index.md 1251 ms
> -----
> Too many errors
> 
> Typos: 7
> 1. njk (6:17, suggest: ngk, kak, njv)
> 2. Следует (39:1, suggest:  Следует)
> 3. кодированных (187:296, suggest: закодированных)
> 4. URI (count: 3, suggest: URL)
> 5. В (suggest:  В)
> 6. Для (suggest:  Для)
> 7. метатега (suggest: мета тега)
> -----
> ```

Лучше бы вынести в отдельный issue.

**Comment by hcodes** [comment]
v10.0.1
