### ISSUE TITLE
Understand apostrophe

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#20]
Right now Yaspeller think that `Sass’s` and `Sass` is different words.

/cc @hcodes

**Comment by hcodes** [comment]
При указании в словаре?
...
```
Как правило, притяжательный падеж образуется присоединением окончания 's к существительному или имени, обозначающему владельца.
```

Сложно понять, `Sass` - это существительное или другая часть речи, при незнании значения слова.

**Comment by ai** [comment]
Да, `Sass` я добавил в словарь.

Тут проблема в символе апострофа. У меня используется не одинарная кавычка `'`, а менно [специальный символ](https://ru.wikipedia.org/wiki/%D0%90%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D1%84) `’`.

**Comment by hcodes** [comment]
Запутался :)
Как должно быть указано в словаре и что ожидается в работе?

Т.е. указываем в словаре `Sass’s`, и при опечатке `Sass` он не должен выводить ошибку?

**Comment by hcodes** [comment]
Или апостроф указан через HTML-entity?

**Comment by ai** [comment]
Указываем Sass, а он должен понимать Sass’s. Это Маркдаун, символ просто введён.

**Comment by hcodes** [comment]
Yaspeller это простая обвертка над API Яндекс.Спеллера.
Не хочется усложнять логику на уровне Yaspeller.
Если в словарь добавить какое-то слово на английском, то не всегда правильно будет работать проверка с притяжательным падежом.
`Saas` -> `Sass's` - ок
`Play` -> `Play's` - уже ошибка 

Лучше явно добавлять данный случай в словарь.
