### ISSUE TITLE
Regexp для уточнения мест, где необходима проверка?

### ISSUE THREAD

**Issue by belyanskii** [hcodes/yaspeller#28]
Есть ли на данный момент возможность объяснить спеллеру что требуется проверять только слова которые написаны допустим %%{в каких-нибудь таких скобках}%%?

**Comment by hcodes** [comment]
Такой возможности нет.

**Comment by hcodes** [comment]
Можешь привести конкретный случай?
Проверять опечатки в управляющих конструкциях какого-то шаблонизатора?

**Comment by belyanskii** [comment]
@hcodes смысл в пропуске комментариев и проверке орфографии только в местах которые дойдут до пользователя. Тем кто использует i18n это было бы удобно, ведь все вставки текста происходят с использованием хелперов, с помощью которых текст в итоге выгружается для перевода. И выходит что мы получаем что-то вроде i18n('Текст'), и проверять можно только подобные места.

**Comment by hcodes** [comment]
Можно добавить опцию "Проверять в найденном тексте", на вход регулярное выражение.

**Comment by ihoru** [comment]
Подписываюсь. Очень нужна это возможность, так как отдавать яндексу исходники проектов не хочется

**Comment by hcodes** [comment]
Прошёл год ;)

Опция не нужна, теперь есть поддержка stdin:
`egrep -o -e "i18n\('*.'\)" | yaspeller`
