### ISSUE TITLE
Опция, чтобы не выкидывать ошибку когда сервис лежит

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#29]
Для Travis CI можно просто ничего не говорить, если Яндекс слёг. Орфография не так нужна всем проектам, чтобы быть в ней уверенной на 100%.

**Comment by hcodes** [comment]
Тогда проще убрать из Travis CI данную проверку.
Лучшим решением будет - поставить проверку на прекомит.
На Travis CI скорее всего произошло ограничение на количество обращений или на количество проверяемых символов - http://legal.yandex.ru/speller_api/
Для всех пользователей Travis ограничение общее:
- 10 тысяч обращений в сутки
- 10 миллионов символов в сутки

**Comment by ai** [comment]
Проверка идёт слишком долго для прекоммита. Да и нельзя заставить всем кто шлёт PR, ставить прекоммит.

То есть сейчас есть два состояния — всё верно, не работает сервис, есть орфографические ошибки.

Жару может возвращать другой код ошибки в случае неработающего сервиса? А я потом отфильтрую.

**Comment by hcodes** [comment]
Ок, yaspeller  будет возвращать другой код ошибки для данного случая.

**Comment by ai** [comment]
Кстати, а у вас нет плагина для Гульпа?

**Comment by hcodes** [comment]
Да, уже кто-то ещё спрашивал, надо сделать.

**Comment by ai** [comment]
Я могу сделать плагин на этой неделе.

**Comment by ai** [comment]
У проекта же есть JS API? Где он нём почитать?

**Comment by kobezzza** [comment]
Да в общем тут плагин и не нужен, т.к. можно просто использовать gulp-run, например,

```js
var gulp = require('gulp'),
      run = require('gulp-run');

gulp.task('yaspeller', function (cb) {
    run('yaspeller ./').exec()
        .on('error', function (err) {
            console.error(err.message);
            cb();
	})
        .on('finish', cb);
});
```

**Comment by hcodes** [comment]
Отличный плагин, не требующий поддержки :)
Добавил в документацию.
Спасибо, @kobezzza

**Comment by hcodes** [comment]
https://github.com/hcodes/yaspeller/blob/master/lib/exit-codes.js#L3

v2.2.0
