### ISSUE TITLE
Блок для игнорирования

### ISSUE THREAD

**Issue by belyanskii** [hcodes/yaspeller#37]
Есть предложение сделать возможность выделять блоки для игнорирования проверки спеллчекером текста, например как это делает jshint:
```js
/* jshint ignore:start */
/* jshint ignore:end */
```

**Comment by xoxulin** [comment]
:+1:

**Comment by tenorok** [comment]
:+1:

**Comment by hcodes** [comment]
:+1:

**Comment by eGavr** [comment]
При чем надо также понимать HTML-комментарии, например, если хочется проигнорить какой-то блок в  md-файле или прям в HTML.

**Comment by hcodes** [comment]
Да, можно сделать так:

Для игнорирования строки:
```
Tratata <!-- yaspeller ignore --!>

Tratata // yaspeller ignore

Tratata /* yaspeller ignore */
```

Для игнорирования блока:
```
<!-- yaspeller ignore:start --!>
Long long text...
<!-- yaspeller ignore:end --!>
...
// yaspeller ignore:start
Long long text...
// yaspeller ignore:end
...
/* yaspeller ignore:start */
Long long text...
/* yaspeller ignore:end */
```

**Comment by eGavr** [comment]
:+1:

**Comment by tenorok** [comment]
Шикарно!

**Comment by xoxulin** [comment]
По-хорошему, должно еще быть такое:
- исходные коды бьются на семантические блоки в зависимости от mime-type:
 * javascript
    - блок кода
    - блоковый / инлайн комментарий
 * markdown
    - текст
    - code блок
- в настройке должна быть возможность указать какие скоупы в каких mime-type проверять
- тогда можно будет проверять
  * только JSDoc-блоки в классах блоков отдельно, а инлайн комментирование оставлять на откуп разработчикам - это их вотчина,
  * аналогично в MD / HTML etc.

**Comment by hcodes** [comment]
@xoxulin 
Попробую учесть в следующих версиях.

**Comment by hcodes** [comment]
v2.4.0
