### ISSUE TITLE
JS словарь

### ISSUE THREAD

**Issue by belyanskii** [hcodes/yaspeller#38]
Текущий словарь собирается из json файла, который, как мне кажется, довольно трудно поддерживать, как минимум потому, что там нет комментариев :)
Возможно имеет смысл сделать словарь в js формате, где можно будет комментировать и разбивать по смыслу группы слов (спец слов?).

**Comment by hcodes** [comment]
JSON комментарии уже сделал (в конфигах и словарях), будут в версии 2.3.0.

**Comment by hcodes** [comment]
Да, кстати, --only-errors будет работать корректно для JSON-отчёта.
