### ISSUE TITLE
Ошибка при длине переменной в 32 символа

### ISSUE THREAD

**Issue by tenorok** [hcodes/yaspeller#39]
Привет, спасибо за классную тулзу!
Мы используем `yaspeller@2.2.0`.

Обнаружился забавный баг. Спеллер матюгается на любую переменную длинной ровно в 32 символа, например:
```js
// test.js
var preventDefaultAndStopPropagation;
```

```bash
› yaspeller --lang ru test.js

Typos: 1
1. preventDefaultAndStopPropagation
```

**Comment by hcodes** [comment]
http://speller.yandex.net/services/spellservice/checkText?text=%D0%9C%D0%B0%D1%81%D0%BA%D0%B2%D0%B0%20preventDefaultAndStopPropagation

http://speller.yandex.net/services/spellservice/checkText?text=%D0%9C%D0%B0%D1%81%D0%BA%D0%B2%D0%B0%20preventDefaultAndStopPropagation&options=16

**Comment by hcodes** [comment]
Для данного случая нужно использовать опцию ```ignoreLatin: true``` или ```--ignore-latin```

**Comment by tenorok** [comment]
Действительно помогает, спасибо!
Но всё таки ведь это баг?

**Comment by hcodes** [comment]
Поправили на стороне API.
ignoreLatin не нужен.
