### ISSUE TITLE
Нет возможности передать аргументы команде при запуске не в TTY

### ISSUE THREAD

**Issue by levonet** [hcodes/yaspeller#47]
Не знаю почему так, но TeamCity выполняет команду не в терминале.
По этому срабатывает условие:
https://github.com/hcodes/yaspeller/blob/master/lib/cli.js#L56
и команда игнорирует аргументы и ожидает данные в пайп.

Хочется, чтоб в этом месте:
  1. не игнорировались аргументы
  2. приоритет пути к данным из аргументов был выше чем данных из пайп

**Comment by hcodes** [comment]
Да, это известный баг, поправлю в ближайшее время.

**Comment by hcodes** [comment]
v2.8.2
