### ISSUE TITLE
Возможность игнорировать комменты в .js коде

### ISSUE THREAD

**Issue by edele** [hcodes/yaspeller#49]
Проверил исходники большого проекта спеллчекером и он начал ругаться на профессионализмы в комментах. Понятно, что наличие комментов и опечатки в них — проблема, которую нужно решать. Но хотелось бы иметь возможность их игнорить и увидеть опечатки в строках, например.

![image](https://cloud.githubusercontent.com/assets/2607770/17092064/40f090a0-5259-11e6-9cf7-dbfbc133a05b.png)

Кому ещё такое могло бы пригодиться?

**Comment by hcodes** [comment]
Да, уже про такое спрашивали, но нужно было комментарии проверять, а строки нет.
Проверку в js-файлах и других файлах нужно будет вынести в плагины.
Поддержка плагинов в планах, но по срокам ничего сказать не могу.

**Comment by hcodes** [comment]
Для этих целей нужно сделать `eslint-plugin-yaspeller`.

**Comment by perevezencev** [comment]
Не получится реализовать `eslint-plugin-yaspeller` из за того что в правилах eslint [нельзя использовать асинхронный код]( https://stackoverflow.com/questions/33881778/asynchronous-code-in-custom-eslint-rules).

**Comment by hcodes** [comment]
Интересно, не знал об этом.
P.S.: Значит настало время сделать поддержку плагинов.
