### ISSUE TITLE
Опции для возможности указания стиля написание

### ISSUE THREAD

**Issue by evilebottnawi** [hcodes/yaspeller#50]
Варианты: Hyphens(some-word), Underscores(some_word) или camelCase(someWord). 
Возможное решение - перед отправление проверять стиль написания на регулярном выражении и если передан параметр указывающий на стиль написания, то преобразовывать текст в написание(удалять `-`, `_` при первых двух вариантах или вставлять пробелы и уменьшать первую буквы следующих слов при третьем варианте) понятное Yandex.Speller.
Если нужна помощь я могу сделать PR.

**Comment by hcodes** [comment]
Эта опция нужна для кода (исходных текстов)?
Если да, то лучше сначала по коду пройтись парсером.

**Comment by evilebottnawi** [comment]
@hcodes То есть для каждого языка лучше сделать отдельный плагин? Было бы тогда удобно указывать в настройках регулярные выражения для игнорирования определнных конкструкций в языка, например для php я бы указывал на игнорирование всего текста внутри php, а для проверки самого языка, использовал бы парсер

**Comment by hcodes** [comment]
Да, плагины.
Нужно «запилить» поддержку плагинов.

**Comment by evilebottnawi** [comment]
@hcodes Я думаю регулярных выражений хватило бы для игнорирования определенного синтаксиса, а саму проверку должны уже осуществлять линтеры `eslint-plugin-yaspeller`, `stylelint-plugin-yaspeller` и так далее.

**Comment by hcodes** [comment]
Совсем забыл, есть возможность использовать pipe'ы.
`egrep -o -e "i18n\('*.'\)" | yaspeller`
Раз про это спрашивают уже несколько человек, нужно «запилить» такую опцию :)

**Comment by evilebottnawi** [comment]
@hcodes `egrap` это хорошая штука, но доступная только на linux, хотелось бы иметь кроссплатформенное решение, а то есть как ты и сказала - добавить опцию

**Comment by hcodes** [comment]
Игнорирование текста при помощи регулярок стало доступно в v2.9.0.
Всё остальное нужно унести в плагины.
