### ISSUE TITLE
Complex regexps are broken

### ISSUE THREAD

**Issue by a-x-** [hcodes/yaspeller#53]
```json
{
  "dictionary": [
    "проксир(ова(нное|нном|в|л|ла|ли|ло|ть)|уем|ует|уете|уешь|уй|уйте|ую|уют|уя)"
  ]
}
```

![2016-08-02_16-28-24](https://cloud.githubusercontent.com/assets/6201068/17330116/8ae807dc-58d6-11e6-9484-fb83ffe96284.png)

**Comment by hcodes** [comment]
@a-x- Проверил на версии 2.9.0 и баг не получилось воспроизвести.
Добавил в словарь - `"проксир(ова(нное|нном|в|л|ла|ли|ло|ть)|уем|ует|уете|уешь|уй|уйте|ую|уют|уя)"`

Создал текстовый файл со словами:
```
Проксированное
Проксированном
проксированное
проксированном
```

**Comment by a-x-** [comment]
Посмотрел, у нас 2.7.0

**Comment by hcodes** [comment]
Установил yaspeller@v2.7.0

Создал конфиг:
```
{
  "lang": "en,ru",
  "format": "auto",
  "fileExtensions": [".md"],
  "excludeFiles": [
    ".*",
    "yaspeller",
    "node_modules",
    "coverage",
    "lib",
    "bin",
    "test"
  ],
  "dictionary": [
    "проксир(ова(нное|нном|в|л|ла|ли|ло|ть)|уем|ует|уете|уешь|уй|уйте|ую|уют|уя)"
  ]
}
```

Создал файл test.md:
```
Проксированном


проксированное
```

Ошибок нет.

**Comment by a-x-** [comment]
Ок, спасибо, из вини за беспокойство.

Может быть у нас грид шалит
