### ISSUE TITLE
yaspeller-ci

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#58]
Hi. Thanks for your awesome project.

I used it on my every opensource project and start worry about making too many requests to Yandex.Speller API. They give it for us for free and we should care about reducing load.

I found two problems:

* I run spelling check on every Node.js version.
* I pass `.js.html` files from JSDoc without a reason.

This is why I created [yaspeller-ci](https://github.com/ai/yaspeller-ci) wrap to reduce requests.

@hcodes

1. What do you think about it?
2. Do I add all links to your project and Yandex service correctly?
3. Do you agree, that it should be separated wrap? I think this optimizations are not for every use case, this is why I created wrap instead of send PR.
4. Do you want to add link to `yaspeller-ci` to your docs?

**Comment by hcodes** [comment]
1. Хорошая идея, чтобы не проверять одно и то же несколько раз.
2. Всё нормально.
3. Да, отдельным проектом.
4. Добавлю.

На одну версию ноды запускается две задачи, если `sudo: false`:
```continuous-integration/travis-ci/pr The Travis CI build passed
continuous-integration/travis-ci/push The Travis CI build passed```
Наверное, хватит одной. Например, только `continuous-integration/travis-ci/pr`.
https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables

Можно проверять не версию ноды, а номер сборки. Выйдет новая версия ноды и нужно будет выпускать новую версию `yaspeller-ci`.

**Comment by hcodes** [comment]
Хорошо бы проверять спеллером только изменённые файлы в PR.

**Comment by ai** [comment]
> Можно проверять не версию ноды, а номер сборки

О! Это огонь! Я как раз волновался, что надо обновлять проект при выходе новой версии. Хочешь послать PR?

**Comment by hcodes** [comment]
Постараюсь.

**Comment by hcodes** [comment]
Ещё вопрос, а зачем нужен чёрный список для `*.js.html`, ведь можно использовать `.yaspellerrc` и свойство `excludeFiles`?

**Comment by ai** [comment]
Кажется, я просто пропустил это свойство 😣

Сегодня попробую его и, если получится, уберу из этого пакета.

Но одну логику (запуск только в первом трейвисе) можно и в ядро перенести, что думаешь?

**Comment by ai** [comment]
Можно с опцию `--ci-once`

**Comment by ai** [comment]
Удалил `*.js.html` хак: https://github.com/ai/yaspeller-ci/commit/551e5be3940c0300737b5b2350759314e75db4a7

Добавил твою идею с `TRAVIS_JOB_NUMBER` https://github.com/ai/yaspeller-ci/commit/d6fce515fafe8954f8eff50709886210a605656b

Если захочешь внести `--cli-once` в `yaspeller`, то я могу задепрекейтить свою библиотеку.

**Comment by hcodes** [comment]
Я иногда использую https://www.appveyor.com/
На Travis не хочется завязываться в yaspellerʼе. Логику про Travis лучше хранить в `.travis.yml`. Там можно на bashʼe написать. Например, [так](https://github.com/bem/bem-components/blob/v5/.travis.yml#L68).

**Comment by ai** [comment]
Попробую добавить appveyor тоже (я его только на PostCSS использую).

Если указать запуск только в `.travis.yml`, то проверка офрографии не будет идти локально при запуске `yarn test`. Но мне с `yaspeller-ci` даже проще, так что на твоё усмотрение :).

**Comment by hcodes** [comment]
Ссылку добавил https://github.com/hcodes/yaspeller#links

Eщё можно прекоммит хук настроить.

**Comment by ai** [comment]
А как ты вообще запускаешь `yaspeller` на AppVeyor?

Я кажется нашёл ошибку:

```
$ yaspeller api/*.html *.md docs/*.md docs/**/*.md
Error: api/*.html: is not exists
Error: *.md: is not exists
Error: docs/*.md: is not exists
Error: docs/**/*.md: is not exists
Checking finished: 0.487 sec.
```

Видимо шаблоны сами не разворачиваются, а шелл-скрипт Windows слишком глупый.

**Comment by ai** [comment]
Выпустил `yaspeller-ci` 0.3 с поддержкой AppVeyor (пока без решения проблемы `*`)
