### ISSUE TITLE
Поддержка Windows и AppVeyor

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#59]
Проблема в том, что в шелл-скрипте Windows (как минимум на AppVeyor) не работает маски `*`.

Поэтому, наверное, куда-то [сюда](https://github.com/hcodes/yaspeller/blob/master/lib/tasks.js#L61) надо вставить проверку на наличие `*` и запуск `glob` вручную.

/cc @hcodes

**Comment by hcodes** [comment]
Это зависит от `shell`. `Bash` раскрывает `*` и передаёт скрипту (yaspeller) все файлы, а MS-DOS нет.
Можно протестировать с помощью небольшого скрипта на ноде.
test.js
```js
console.log(process.argv)
```
В тестируемой папке 3 файла: `test.js`, `a.md` и `b.md`
`node test.js *`

Вывод в CygWin:
```$ node test.js *
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\Denis\\Documents\\GitHub\\test-glob\\test.js',
  'a.md',
  'b.md',
  'test.js' ]
```

Вывод в MS-DOS:
```
c:\Users\Denis\Documents\GitHub\test-glob>node test.js *.js
[ 'C:\\Program Files\\nodejs\\node.exe',
  'c:\\Users\\Denis\\Documents\\GitHub\\test-glob\\test.js',
  '*.js' ]
```

Думаю, что `yaspeller` не должен вручную запускать глобы.

**Comment by ai** [comment]
Есть два контраргумента:

1. На AppVeyor шелл-скрипт сменить нельзя.
2. ESLint и Babel делают glob.

Я бы исправил проблему в ядре. Но если не хочешь заниматься Виндой, я могу сделать это в yaspeller-ci.

**Comment by hcodes** [comment]
Аргументы принимаются. Про второе не знал, посмотрю подробнее.

**Comment by hcodes** [comment]
Совсем забыл, можно так`yaspeller -e ".md,.html,.js"`. Некий аналог для звёздочек.

**Comment by ai** [comment]
Да, терпимо для временного решения. Но поскольку до него никто не додумается и оно не гибкое, то лучше сделать как в ESLint, Babel.

**Comment by ai** [comment]
Если хочешь, я могу послать людей с Cult of Martians.

**Comment by hcodes** [comment]
Не надо, сам запилю.

**Comment by retyui** [comment]
@hcodes Работаю под win10👽 и испытываю эту проблему , очень жду обновления 🔥0.3.3🔥
Спасибо за ваш труд👍!

**Comment by hcodes** [comment]
Поддержку сделал, но захотелось порефакторить и дописать тесты,  на этом и застрял. (

**Comment by hcodes** [comment]
v3.3.0
