### ISSUE TITLE
Add hyphen support to the dictionary

### ISSUE THREAD

**Issue by vessd** [hcodes/yaspeller#64]
Не знаю насколько это правильно, но мне бы хотелось добавить в словарь "борроу-чекер".
На данный это не работает. Приходиться добавлять как два отдельных слова.

**Comment by hcodes** [comment]
В словаре можно сделать так, чтобы такое слово внутренне представлялось как два слова.

**Comment by vessd** [comment]
Пока не очень понял. Добавить как два отдельных слова? Вариант конечно, но не хочется его использовать.
Вот например слово "потоко-специфичные". Мне его только в таком виде хочется разрешить.

**Comment by hcodes** [comment]
Да, как два отдельных слова.

API Яндекс.Спеллера проверяет сложные слова по отдельности.
![yaspeller](https://cloud.githubusercontent.com/assets/157520/23825386/f369d47c-0699-11e7-8a34-e80c038c30db.png)

**Comment by hcodes** [comment]
Добавляем в словарь "потоко-специфичные", а он разбивает у себя внутри на два слова "потоко" и "специфичные". Небольшой хелпер.

**Comment by vessd** [comment]
Ну вот при добавлении в словарь "потоко-специфичные" он всё равно жалуется на слово "потоко", считая его отдельным. Разрешать просто "потоко" не хочется, ведь это не корректно.

**Comment by hcodes** [comment]
Разбор слов и поиск опечаток производится на стороне API Яндекс.Спеллера. Вкручивать дополнительную логику в данный код не хочется.
