### ISSUE TITLE
[Feature request] Line and column numbers in begin or end of output line

### ISSUE THREAD

**Issue by Kristinita** [hcodes/yaspeller#68]
### 1. Request

Было бы неплохо, если б в выводе yaspeller в консоль номера строк и столбцов располагались бы в начале или конце, но не середине.

Вероятно, если данный запрос будет удовлетворён, это поможет сделать более качественным yaspeller-линтер для Sublime Text.

я не смог придумать, какие проблемы могут возникнуть, если запрос будет удовлетворён.

### 2. Steps to reproduce

Например, я ввожу в терминале:

```shell
yaspeller myfile.md
```

### 3. Actual behavior

Некоторые строки из вывода:

```shell
6. веганский (245:78)
9. Боруссии (272:48, suggest: Белоруссии)
63. Кристиниты (1084:80, count: 4, suggest: Кристины, Кристинины)
```

### 4. Expected behavior

Например, так. Лишь бы номера столбцов и строк были где-нибудь в начале или конце.

```shell
6. веганский (245:78)
9. Боруссии (suggest: Белоруссии) (272:48)
63. Кристиниты (count: 4, suggest: Кристины, Кристинины) (1084:80)
```

### 5. Settings

Пишу [**пакет для Sublime Text**](http://kristinita.ru/Sublime-Text/ValeriyaSpeller). С помощью моего пакета yaspeller подсвечивает слова, которые считает ошибочными, прямо в тексте, пример:

![yaspeller example](http://i.imgur.com/Hzaquml.png)

### 6. Justification

Для работы моего линтера необходимо составить [**регулярное выражение**](http://www.sublimelinter.com/en/latest/linter_attributes.html?highlight=near#regex), которое парсит вывод yaspeller в консоли. [**Пример для моего пакета**](https://github.com/Kristinita/SublimeLinter-contrib-ValeriyaSpeller/blob/SashaDevelop/linter.py#L50-#L54).

Проблема состоит в том, что у меня не получается сделать регулярное выражение, захватывающее всю строку полностью. Например, для

```shell
63. Кристиниты (1084:80, count: 4, suggest: Кристины, Кристинины)
```

я могу сделать, чтобы во всплывающей подсказке отображалось:

1. [**Первый вариант**](https://github.com/Kristinita/SublimeLinter-contrib-ValeriyaSpeller/blob/SashaDevelop/linter.py#L50-#L54) — `Кристиниты`

или

2. [**Второй вариант**](https://github.com/Kristinita/SublimeLinter-contrib-ValeriyaSpeller/commit/8b10a03a59fa5786543ab9a49f93f8329b36dd47#diff-6c1f4f1574c85da37dc4dd59341c9a39) — `count: 4, suggest: Кристины, Кристинины`

Но не могу сделать так, чтобы отображалась строка полностью.

Если нужны дополнительные технические подробности, пожалуйста, спрашивайте.

### 7. Not helped

1. Читал документации SublimeLinter и Яндекс.Спеллер.
1. Смотрел, как интегрированы в Sublime Text другие линтеры и спеллчекеры → в тех, которые смотрел, номера столбца и строки с ошибкой располагаются в начале или конце строки.

Вероятно, без изменений в yaspeller мне не удастся сделать так, чтобы во всплывающей подсказке полностью отображалась бы вся строка.

### 8. Examples on other apps

Спеллчекер [**write-good**](https://github.com/btford/write-good), [**пакет write-good для Sublime Text**](https://github.com/ckaznocha/SublimeLinter-contrib-write-good).

Пример вывода в консоли:

```shell
Multiple saving of links on services of a caching of web resources
^^^^^^^^
"Multiple" is wordy or unneeded on line 5 at column 0
```

Пакет write-good для Sublime Text в действии:

![write-good](http://i.imgur.com/TbohGfc.png)

Спасибо.

**Comment by hcodes** [comment]
Распарсить консоль можно такой регуляркой:
```js
'6. веганский (245:78)'.match(/\((\d+):(\d+)[),]/)
// Array [ "(245:78)", "245", "78" ]
```

В yaspeller’е есть возможность формировать собственные отчёты.
Пример генератора отчёта — https://github.com/hcodes/yaspeller/blob/master/lib/report/example.js
```
yaspeller --report ./путь/example.js --lang ru my_text.txt
```

Для написания плагинов лучше использовать node.js-пакет `yandex-speller` https://github.com/hcodes/yandex-speller
Он лёгкий, не имеет зависимостей и простое API.

**Comment by hcodes** [comment]
@Kristinita Остались ли ещё вопросы?

**Comment by Kristinita** [comment]
@hcodes , прошу прощения, я в командировке, у меня нет доступа к ПК. Позже отпишусь.

Спасибо.

**Comment by hcodes** [comment]
Может подойдёт: https://github.com/oriontvv/pyaspeller

**Comment by hcodes** [comment]
В [gist](https://gist.github.com/hcodes/83e5da73caf118b8363689048ab106e5) положил модуль с собственным отчётом, номер строки и колонка находятся в конце строки.
`yaspeller -l ru --report="Абсолютный путь/my_console.js" https://habr.ru`

Пример вывода:
```
[ERR] https://habr.ru 237 ms
-----
Typos: 27
1. Фрилансим (suggest: Фрилансом, 156:109)
2. Мегапосты (count: 2, 159:36)
3. Хабы (count: 2, 183:52)
4. Хабр (count: 2, 333:12)
5. Хабре (334:14)
6. айтишников (630:203)
7. Иннополис (suggest: Аннаполис, 638:233)
8. Раскурочивание (count: 3, suggest: Раскулачивание, Раскручивание, Расказачивание, 761:89)
9. оперативы (count: 4, 761:168)
10. БП (786:207)
11. электрошокер (786:332)
12. вендор (790:90)
13. ребилды (790:432)
14. капасити (790:587)
15. инди (count: 2, 996:88)
16. Вейера (suggest: Веера, Вечера, Вера, Венера, Вебера, 1118:77)
17. Уотни (suggest: Уитни, Сотни, Утони, Уютный, 1118:127)
18. Ингипро (count: 2, suggest: Инги про, 1325:53)
19. прототипирования (1383:104)
20. фотобанках (1410:143)
21. прототипирование (1412:263)
22. мердок (suggest: Мэрдок, 1530:122)
23. НеПетю (suggest: Не Петю, 1654:208)
24. хотспотов (suggest: хот спотов, 1797:315)
25. кибератаке (count: 2, suggest: кибер атаке, 1818:253)
26. КРОК
27. Хабрахабр (count: 4)
-----
```
