### ISSUE TITLE
Documentation only

### ISSUE THREAD

**Issue by azat-io** [hcodes/yaspeller#69]
Hi!

I do not need to check names of variables in my JavaScript code. 
But I want to check JSDoc tags. Looks like it is not possible now, but it'll be very helpful

**Comment by hcodes** [comment]
One of solutions:
`grep -Pzo '\/\*\*(\n|.)*?\*\/' my_file.js | yaspeller -l en`

**Comment by azat-io** [comment]
@hcodes Thanks.
I found a solution of my problem using [yaspeller-ci](https://github.com/ai/yaspeller-ci)
