### ISSUE TITLE
Error: connect ETIMEDOUT 213.180.204.29:443

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#74]
Серсерва Яндекса уже пару дней иногда не отвечают и CI заканчивается ошибкой.

Пример: https://travis-ci.org/logux/logux-sync/jobs/269144370

Может делать 3-5 попыток в случае отсутствия связи?

**Comment by hcodes** [comment]
Хорошая идея, надо сделать.

**Comment by ai** [comment]
Помощь нужна?

**Comment by hcodes** [comment]
Было бы не плохо, не знаю когда дойду до этой задачи.
Править нужно где-то [здесь](https://github.com/hcodes/yandex-speller/blob/master/lib/post.js#L41).

**Comment by ai** [comment]
Отправлю ребят с http://cultofmartians.com/

**Comment by rodweb** [comment]
Пулреквест нужно прислать в [hcodes/yandex-speller](https://github.com/hcodes/yandex-speller), получается?

**Comment by hcodes** [comment]
Ага.

**Comment by Avetome** [comment]
https://github.com/hcodes/yandex-speller/pull/1

**Comment by hcodes** [comment]
👍
