### ISSUE TITLE
Функциональность glob-паттернов

### ISSUE THREAD

**Issue by lamartire** [hcodes/yaspeller#75]
Привет!
Допустим, у нас есть проект с подобной структурой:
```
src/
  locale/
    ru/
      dir1/
        subdir1/
           b.json
        a.json
    en/
      dir1/
        c.json
```
В текущей реализации, если запустить утилиту подобным образом `yaspeller src/**/*.json` ни один из файлов проверен не будет, для того, чтобы проверить все json файлы, придется делать что-то вроде `yaspeller src/locale/**/*.json src/locale/ru/**/*.json src/locale/en/**/*.json ...`, грубо говоря --указывать каждый уровень вложенности вайлдкардом, что не очень круто.

Существует какое-нибудь решение, чтобы заставить обрабатываться все файлы по заданному расширению в директории и ее поддиректориях?

**Comment by hcodes** [comment]
Должно помочь: `yaspeller -e ".json" src/`
Со звёздочками посмотрю…

**Comment by lamartire** [comment]
> Должно помочь: yaspeller -e ".json" src/

Помогло, спасибо :)
