### ISSUE TITLE
[Nightmare/Phantom] Прокидывать загруженные страницы

### ISSUE THREAD

**Issue by Tsympil** [hcodes/yaspeller#81]
Возможно ли прокидывать загруженную страницу через Nightmare/Phantom в утилиту, чтобы для каждой отданной страницы получать результат и уже его по-своему обрабатывать?

**Comment by hcodes** [comment]
Можно использовать https://github.com/hcodes/yandex-speller/
Метод `checkText`.

**Comment by Tsympil** [comment]
Всё прекрасно, но есть ли там возможность передавать массив **ignoreText**?

**Comment by hcodes** [comment]
Нет.
