### ISSUE TITLE
Bug: yaspeller returns exit code 0 when receives non-existing file as a parameter

### ISSUE THREAD

**Issue by inem** [hcodes/yaspeller#90]
When I use it inside CI system, I expect it to fail in such situations.

**Comment by hcodes** [comment]
Behavior like eslint.
![seles fish users seles -fish 67x11 2017-11-15 23-29-53](https://user-images.githubusercontent.com/157520/32858551-edee3920-ca5c-11e7-9fc5-cbc912319190.png)

**Comment by inem** [comment]
Hmm. This looks weird to me. Is there a real reason behind this behavior?

**Comment by hcodes** [comment]
Use shell scripts for this. No a file, no typos. :)
