### ISSUE TITLE
Question: speller don`t understand camelcase words

### ISSUE THREAD

**Issue by iandreyshev** [hcodes/yaspeller#91]
Is it possible to make a camelcase words reading correctly?

**Comment by hcodes** [comment]
mySuperVariable → my super variable?

**Comment by iandreyshev** [comment]
I made a mistake by writing "split". I wanted to say that, speller return error on word in camel case, but the word can be written without errors.
For example:
buttonName - this is correct word, but speller return error

**Comment by hcodes** [comment]
Yandex Speller.API does not support this. Should be a separate option.
