### ISSUE TITLE
[Feature request] Non UTF-8 support

### ISSUE THREAD

**Issue by Kristinita** [hcodes/yaspeller#92]
### 1. Request

Было бы неплохо, если бы yaspeller поддерживал кодировку Windows-1251.

### 2. Justification

По некоторым причинам (из-за устаревшего ПО не получается перейти на UTF-8) в текстовых файлах приходится использовать кодировку Windows-1251. yaspeller не проверяет файлы в данной кодировке.

### 3. Settings

+ yaspeller 3.3.0.

Содержимое файла `SashaExample.txt`:

```markdown
Sasha Belissimo!

Саша Совершенна!
```

### 4. Actual behavior

Если файл сохранён в Windows-1251:

```shell
D:\SashaPythonista>yaspeller "SashaExample.txt"
Error: D:\SashaPythonista\SashaExample.txt: is not utf-8
Checking finished: 0.409 sec.
```

### 5. Expected behavior

Если этот же файл сохранён в UTF-8:

```shell
D:\SashaPythonista>yaspeller "SashaExample.txt"
[ERR] D:\SashaPythonista\SashaExample.txt 408 ms
-----
Typos: 3
1. Sasha (1:1, suggest: Саша, Sasha)
2. Belissimo (1:7, suggest: Белиссимо, Bellissimo, Беллиссимо, Belisimo, Belissima, Bellissima, Белисимо, Bellisimo, Беллисимо)
3. Совершенна (3:6, suggest: Совершенно, Совершена, Совершенная)
-----

Checking finished: 0.941 sec.
```

Спасибо.

**Comment by hcodes** [comment]
`Windows-1251` устаревшая кодировка, используйте всегда и везде `UTF-8`.
Могу порекомендовать консольную утилиту `iconv` для решения текущей проблемы:
`iconv -f WINDOWS-1251 -t UTF-8 src_filename | yaspeller`
