### ISSUE TITLE
ignoreDigits не работает, регулярка типа [0-9]\. не работает, что делать ?

### ISSUE THREAD

**Issue by Nazirkulov** [hcodes/yaspeller#93]
Ругается на текст типа: 5. 1. итд , пробовал в файле конфига "ignoreDigits": true , --ignore-digits 
пробовал "(1|2|3|4|5|7|8|9|0)\.?", "(1|2|3|4|5|7|8|9|0)\." , "[0-9]\."

**Comment by hcodes** [comment]
Какая версия Yaspeller?

**Comment by hcodes** [comment]
<img width="697" alt="screenshot" src="https://user-images.githubusercontent.com/157520/35103048-d597413c-fc75-11e7-904a-15bc054e8424.png">

**Comment by Nazirkulov** [comment]
"yaspeller": "^4.0.3"

**Comment by Nazirkulov** [comment]
![screenshot_7](https://user-images.githubusercontent.com/26059370/35103460-eed27ddc-fc76-11e7-8f8c-25ed09dcdb7e.png)
что он сообщает ?

**Comment by Nazirkulov** [comment]
понял что yaspeller ругался на вопросительные знаки
