### ISSUE TITLE
.yaspellerrc не отслеживает лишние ключи

### ISSUE THREAD

**Issue by NtsDK** [hcodes/yaspeller#94]
Довольно легко в .yaspellerrc добавить не обрабатываемые ключи.
В частности я добавил по ошибке check-yo вместо checkYo. Соответствующее checkYo значение извлекалось из настроек по умолчанию, а check-yo просто игнорировалось.
Предлагаю добавить хоть какое-нибудь сообщение о том, что в .yaspellerrc находятся не ожидаемые ключи.

**Comment by hcodes** [comment]
+1

**Comment by hcodes** [comment]
v4.1.0
