### ISSUE TITLE
Интерактивное исправление ошибок

### ISSUE THREAD

**Issue by dima74** [hcodes/yaspeller#97]
Аналогично https://github.com/hcodes/eyo/issues/16:

Было бы здорово иметь возможность интерактивно исправлять ошибки. То есть для слов, для которых Яндекс.Спеллер предлагает исправление(-ия), выводить его(их) с контекстом (несколько слов рядом с ошибочным словом), далее считывать клавиши принятия/непринятия исправления и на основе этого принимать решение о произведении исправления. В конце интерактивного исправления ошибок предлагается перезаписать обрабатываемый файл(файлы).

**Comment by hcodes** [comment]
Не планируется.
