### ISSUE TITLE
Настройки в package.json

### ISSUE THREAD

**Issue by ai** [hcodes/yaspeller#99]
Иногда хочется собрать настройки всех инструментов в одном месте. Сейчас практически все инструменты поддерживают настройки в `package.json`.

[`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) позволит легко поддерживать оба файла конфига.

**Comment by hcodes** [comment]
Да, хорошая идея, надо сделать.

**Comment by ai** [comment]
Отлично. Я тогда отправлю людей с Культа Марсиан. Хорошая задача для новичков.

**Comment by shashkovdanil** [comment]
https://github.com/hcodes/yaspeller/pull/101

**Comment by thepocp** [comment]
Почему-то мой PR остался незамеченным(

**Comment by ai** [comment]
@thepocp надо было писать в сюда.

Пусть теперь @hcodes выбирает.

**Comment by thepocp** [comment]
@ai Понял, учту на будущее

**Comment by hcodes** [comment]
v4.2.0
